# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2dc9612244f34d7a63fe2602c8d5c4c3f91aca53f1eafa163e76c721dab8dead3b24d6d2f814a13c93a97af9007d9b4f3fe90826c5f070df2d0cf4963abd4880

test:
  secret_key_base: a49130e0de02da36d56ec0733438f20645c9ca00483499f56e681ff0066df6a329fb5b20e72b229b81e646b007957b096000e0beed8e4ff16f8510392e961f4e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
